server:
  url: "http://localhost:8080/probe_results"
  task_url: "http://localhost:8080/probe_task"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "my_exchange"

  # ICMP 队列
  icmp_task_queue: "icmp_task_queue"
  icmp_result_queue: "icmp_result_queue"
  icmp_task_routing_key: "icmp_task_routing_key"
  icmp_result_routing_key: "icmp_result_routing_key"

  # TCP 队列
  tcp_task_queue: "tcp_task_queue"
  tcp_result_queue: "tcp_result_queue"
  tcp_task_routing_key: "tcp_task_routing_key"
  tcp_result_routing_key: "tcp_result_routing_key"

log_file: "./client/logs/client.log" # 日志文件路径，确保路径与 Dockerfile 中一致

concurrency:
  icmp: 100
  tcp: 100